// Source of truth for the Content-Security-Policy. The headers() in next.config.ts serves it.
//
// src/proxy.ts used to issue a per-request CSP with a nonce, but Next 16's proxy runs only on
// the Node runtime, and OpenNext (Cloudflare Workers) does not support Node middleware, so it
// could not be migrated. The nonce was dropped in favor of a static header.
//
// script-src needs 'unsafe-inline' because Next's bootstrap (self.__next_f.push) is
// inline. ld+json is a data block and is not executed, so it is outside script-src.
//
// Widened in two places for the Cloudflare Web Analytics beacon. The script itself is loaded
// from static.cloudflareinsights.com, and measurements are POSTed to
// cloudflareinsights.com. **If either is missing the page still looks fine while only the
// beacon is silently blocked**, so csp.test.ts pins both.
//
// extraImgSrc is the list of origins for the official link card at the end of articles (OGP images shown directly).
// JSON is not read here but taken as an argument, keeping this function pure with no I/O.
// The list is generated by scripts/fetch-og-cards.mjs and read by next.config.ts.
export function contentSecurityPolicy({
  dev = false,
  extraImgSrc = [],
}: { dev?: boolean; extraImgSrc?: readonly string[] } = {}): string {
  return [
    "default-src 'self'",
    `script-src 'self' 'unsafe-inline' https://static.cloudflareinsights.com${dev ? " 'unsafe-eval'" : ""}`,
    "style-src 'self' 'unsafe-inline'",
    "font-src 'self'",
    ["img-src 'self' data:", ...extraImgSrc].join(" "),
    "connect-src 'self' https://cloudflareinsights.com",
    "manifest-src 'self'",
    "frame-ancestors 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "object-src 'none'",
    "upgrade-insecure-requests",
  ].join("; ");
}
