import { readFileSync } from "node:fs";
import type { NextConfig } from "next";
import { contentSecurityPolicy } from "./src/lib/csp";

// Origins allowed for the official link card at the end of articles (OGP images shown directly).
// The list is generated by scripts/fetch-og-cards.mjs. src/proxy.ts used to import it,
// but middleware was removed, so it is read here. readFileSync is used so we do not depend on
// whether Next's config loader can resolve JSON imports.
const ogImageHosts: string[] = JSON.parse(
  readFileSync(new URL("./content/og-image-hosts.json", import.meta.url), "utf8"),
);

// src/lib/csp.ts is the source of truth for the CSP.
const securityHeaders = [
  {
    key: "Content-Security-Policy",
    value: contentSecurityPolicy({
      dev: process.env.NODE_ENV !== "production",
      extraImgSrc: ogImageHosts,
    }),
  },
  { key: "Strict-Transport-Security", value: "max-age=63072000; includeSubDomains; preload" },
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "X-Frame-Options", value: "DENY" },
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
  { key: "Cross-Origin-Opener-Policy", value: "same-origin" },
  { key: "X-DNS-Prefetch-Control", value: "on" },
  {
    key: "Permissions-Policy",
    value: "geolocation=(), camera=(), microphone=(), payment=(), usb=(), interest-cohort=()",
  },
];

const nextConfig: NextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  // Article Markdown is read with fs at runtime, so bundle it into the server bundle.
  outputFileTracingIncludes: {
    "/**": ["./content/**/*"],
  },
  // Permanently redirect the old URL (workers.dev) and www to the canonical domain.
  // Moved to the custom domain on 2026-09-23. Keep in sync with BASE_URL (src/engine/site.ts).
  // The root needs its own rule: with an empty path, OpenNext left ":path*" unreplaced
  // and redirected "/" to the literal "https://serviceanatomy.com/:path*" (404).
  async redirects() {
    return ["service-anatomy.saitotakuya0719.workers.dev", "www.serviceanatomy.com"].flatMap((host) => {
      const has = [{ type: "host" as const, value: host }];
      return [
        { source: "/", has, destination: "https://serviceanatomy.com/", permanent: true },
        { source: "/:path+", has, destination: "https://serviceanatomy.com/:path+", permanent: true },
      ];
    });
  },
  async headers() {
    return [{ source: "/:path*", headers: securityHeaders }];
  },
};

export default nextConfig;
