import fs from "node:fs";
import path from "node:path";

// Loads content/og-cards.json generated by scripts/fetch-og-cards.mjs.
// Metadata for the "official link card" at the end of articles; images are shown directly
// from each company's server (not copied to our server). Non-https URLs are dropped.

export interface OgCard {
  url: string;
  title?: string;
  description?: string;
  image?: string;
  siteName?: string;
}

function sanitizeCard(value: unknown): OgCard | undefined {
  if (typeof value !== "object" || value === null) {
    return undefined;
  }
  const record = value as Record<string, unknown>;
  if (typeof record.url !== "string" || !record.url.startsWith("https://")) {
    return undefined;
  }
  const card: OgCard = { url: record.url };
  for (const key of ["title", "description", "siteName"] as const) {
    const text = record[key];
    if (typeof text === "string" && text.trim() !== "") {
      card[key] = text;
    }
  }
  if (typeof record.image === "string" && record.image.startsWith("https://")) {
    card.image = record.image;
  }
  return card;
}

/** Loads og-cards.json and returns it with invalid entries removed. */
export function loadOgCards(
  filePath: string = path.join(process.cwd(), "content", "og-cards.json"),
): Record<string, OgCard> {
  if (!fs.existsSync(filePath)) {
    return {};
  }
  const raw = JSON.parse(fs.readFileSync(filePath, "utf8")) as Record<string, unknown>;
  const cards: Record<string, OgCard> = {};
  for (const [slug, value] of Object.entries(raw)) {
    const card = sanitizeCard(value);
    if (card) {
      cards[slug] = card;
    }
  }
  return cards;
}
